### ISSUE TITLE
MGLM version no longer appears compatible

### ISSUE THREAD

**Issue by haslamdb** [qunfengdong/DMBC#2]
Hi, I believe a couple of your functions rely on the ddirm function from MGLM package. The newest version of MGLM (0.0.9) no longer has a function ddirm. It is now called ddirmn. As a consequence, some of the functions in DMBC fail. I got around this by installing older version (0.0.8) of MGLM from source, but I wonder if you would need to modify your code based on new MGLM.

Thanks for a great package!
David Haslam

**Comment by qunfengdong** [comment]
Dear David:

Thanks for brining this to our attention.  We will try to modify the code
based on new MGLM.  Until it is done, we will also make a note for users to
install the older version of MGLM for now.

We are also open for collaborations to apply DMBC to your dataset if
necessary.  The current version of DMBC is our first attempt towards
applying microbiome data for disease diagnosis, but we only had access to
limited dataset for our development efforts.  We anticipate to further
improve it with additional data.

Best regards,
Qunfeng Dong

**Comment by xianggao2006** [comment]
Thank you David. We have updated our code to use ddirmn function, based on your suggestion.

**Comment by haslamdb** [comment]
Hi Qunfeng,

We actually have a lot of data. I would be interested in collaborating with you on this as we'd like to include in a manuscript. I would only be able to offer you middle-authorship as it will be part of a larger project. Would that be ok with you?

Feel free to email me at dbhaslam@gmail.com or david.haslam@cchcm.org

Best regards,
David
